name: Final Project and Railway Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker image
      run: |
        docker build -t my-node-app:latest .
   
    - name: Install Dependencies
      run: npm install

    - name: Run Sequelize
      env:
        NODE_ENV: production
        PGHOST: ${{ secrets.DB_HOST }}
        PGPORT: ${{ secrets.DB_PORT }}
        PGDATABASE: ${{ secrets.DB_NAME }}
        PGUSER: ${{ secrets.DB_USER }}
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        npm install -g sequelize-cli
        npx sequelize db:create || echo "Database already exists, skipping creation"
        npx sequelize db:migrate
        npx sequelize db:seed:all

    - name: Run Tests
      run: |
        docker-compose up -d db
        docker run --network="host" my-node-app:latest npm test -- --passWithNoTests

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh 

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway up --service final_project_backend_hacktive8